# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  sdaonline2csharpbackendteamwork1:
    image: sdaonline2csharpbackendteamwork1
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5110:5110
